# This is the default config file for ProxyBypass.
# This config was generated for version ${project.version}.

# The IP addresses of the proxy servers.
# If you want to whitelist multiple proxy servers, you can just add multiple IP addresses.
# IMPORTANT: Do NOT use '0.0.0.0' or '127.0.0.1' as an IP address.
# IMPORTANT: Do NOT enter a port here.
proxy-addresses:
  - 127.0.0.1

# The message when a player does not join over one of the proxies.
# You can use '\n' to go to a new line.
kick-message: "&cPlease join directly on example.com! \n &aThis is the default message."